/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ta_pbo;

import javax.swing.JOptionPane;

/**
 *
 * @author Nabil Rizki
 */
public class index extends javax.swing.JFrame {

    /**
     * Creates new form index
     */
    public index() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        RKubus = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tinggi = new javax.swing.JTextField();
        panjang = new javax.swing.JTextField();
        lebar = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        RBola = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        RTabung = new javax.swing.JTextField();
        TTabung = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                formComponentMoved(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));
        jPanel2.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel5.setText("Panjang");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(40, 30, 120, 30);
        jPanel2.add(RKubus);
        RKubus.setBounds(120, 30, 260, 30);

        jButton3.setText("Hitung Volume");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);
        jButton3.setBounds(120, 70, 140, 30);

        jButton4.setText("Hitung Luas ");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);
        jButton4.setBounds(280, 70, 100, 30);

        jTabbedPane1.addTab("KUBUS", jPanel2);

        jPanel1.setBackground(new java.awt.Color(204, 153, 255));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel2.setText("Tinggi");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 110, 120, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel3.setText("Panjang");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 30, 120, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel4.setText("Lebar");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(40, 70, 120, 30);
        jPanel1.add(tinggi);
        tinggi.setBounds(120, 110, 190, 30);
        jPanel1.add(panjang);
        panjang.setBounds(120, 30, 190, 30);
        jPanel1.add(lebar);
        lebar.setBounds(120, 70, 190, 30);

        jButton1.setText("Hitung Luas ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(320, 70, 120, 30);

        jButton2.setText("Hitung Volume");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(320, 30, 120, 30);

        jTabbedPane1.addTab("BALOK", jPanel1);

        jPanel4.setBackground(new java.awt.Color(255, 153, 255));
        jPanel4.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel6.setText("Jari-jari");
        jPanel4.add(jLabel6);
        jLabel6.setBounds(40, 40, 120, 16);
        jPanel4.add(RBola);
        RBola.setBounds(120, 30, 240, 30);

        jButton5.setText("Hitung Volume");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton5);
        jButton5.setBounds(120, 70, 130, 30);

        jButton6.setText("Hitung Luas ");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton6);
        jButton6.setBounds(260, 70, 100, 30);

        jTabbedPane1.addTab("BOLA", jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 153, 153));
        jPanel5.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel8.setText("Jari-jari");
        jPanel5.add(jLabel8);
        jLabel8.setBounds(40, 36, 120, 20);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel9.setText("Tinggi");
        jPanel5.add(jLabel9);
        jLabel9.setBounds(40, 76, 120, 20);
        jPanel5.add(RTabung);
        RTabung.setBounds(120, 30, 250, 30);
        jPanel5.add(TTabung);
        TTabung.setBounds(120, 70, 250, 30);

        jButton7.setText("Hitung Luas ");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton7);
        jButton7.setBounds(270, 110, 100, 30);

        jButton8.setText("Hitung Volume");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton8);
        jButton8.setBounds(120, 110, 130, 30);

        jTabbedPane1.addTab("TABUNG", jPanel5);

        jPanel3.setBackground(new java.awt.Color(153, 255, 153));
        jPanel3.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel7.setText("Sisi Miring");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(40, 116, 120, 20);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel10.setText("Jari-jari");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(40, 36, 120, 20);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel11.setText("Tinggi");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(40, 76, 120, 20);
        jPanel3.add(jTextField6);
        jTextField6.setBounds(120, 110, 190, 30);
        jPanel3.add(jTextField9);
        jTextField9.setBounds(120, 30, 190, 30);
        jPanel3.add(jTextField10);
        jTextField10.setBounds(120, 70, 190, 30);

        jButton9.setText("Hitung Luas ");
        jPanel3.add(jButton9);
        jButton9.setBounds(320, 70, 100, 30);

        jButton10.setText("Hitung Volume");
        jPanel3.add(jButton10);
        jButton10.setBounds(320, 30, 100, 30);

        jTabbedPane1.addTab("KERUCUT", jPanel3);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 0, 470, 210);

        setSize(new java.awt.Dimension(483, 248));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentMoved

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        int r = Integer.parseInt(RKubus.getText().toString());
        int v = r*r*r;
        JOptionPane.showMessageDialog(null,"Volume = " + v);
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int r = Integer.parseInt(RKubus.getText().toString());
        int v = r*r*6;
        JOptionPane.showMessageDialog(null,"Luas Permukaan = " + v);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int p = Integer.parseInt(panjang.getText().toString());
        int l = Integer.parseInt(lebar.getText().toString());
        int t = Integer.parseInt(tinggi.getText().toString());
        int v = p*l*t;
        JOptionPane.showMessageDialog(null,"Volume  = " + v);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int p = Integer.parseInt(panjang.getText().toString());
        int l = Integer.parseInt(lebar.getText().toString());
        int t = Integer.parseInt(tinggi.getText().toString());
        int v = 2*((p*l)+(p*t)+(l*t));
        JOptionPane.showMessageDialog(null,"Luas Permukaan  = " + v);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        
        int r = Integer.parseInt(RBola.getText().toString());
        Double v = (4/3.0*22/7)*r*r*r;
        JOptionPane.showMessageDialog(null,"Volume  = " + v);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        int r = Integer.parseInt(RBola.getText().toString());
        Double v = (4.0*22/7)*r*r;
        JOptionPane.showMessageDialog(null,"Luas Permukaan  = " + v);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        int r = Integer.parseInt(RTabung.getText().toString());
        int t = Integer.parseInt(TTabung.getText().toString());
        Double v = (22/7.0*r*r)*t;
        JOptionPane.showMessageDialog(null,"Volume  = " + v);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        int r = Integer.parseInt(RTabung.getText().toString());
        int t = Integer.parseInt(TTabung.getText().toString());
        Double v = (2.0*22/7*r*r)+(22/7.0*(2*r)*t);
        JOptionPane.showMessageDialog(null,"Luas Permukaan  = " + v);
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new index().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField RBola;
    private javax.swing.JTextField RKubus;
    private javax.swing.JTextField RTabung;
    private javax.swing.JTextField TTabung;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField lebar;
    private javax.swing.JTextField panjang;
    private javax.swing.JTextField tinggi;
    // End of variables declaration//GEN-END:variables
}
